apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: __AKS_DEPLOYMENT_NAME__
  namespace: applications
  annotations:
    konghq.com/plugins: app-searchia-key-auth
spec:
  ingressClassName: kong
  rules:
    - http:
        paths:
          - path: /assistant
            pathType: Prefix
            backend:
              service:
                name: __AKS_DEPLOYMENT_NAME__
                port:
                  number: 80