apiVersion: v1
kind: Secret
metadata:
  name: __AKS_DEPLOYMENT_NAME__-secrets
  namespace: __AKS_NAMESPACE__
type: Opaque
stringData:
  azure.search.api-key: __AZURE_SEARCH_API_KEY__
  azure.openai.api-key: __AZURE_OPENAI_API_KEY__
