apiVersion: v1
kind: Secret
metadata:
  name: app-searchia-jwt-credential
  namespace: applications
type: Opaque
stringData:
  kongCredType: jwt

  # Debe coincidir con el issuer del JWT
  key: "http://keycloak.172.168.4.116.nip.io/realms/microservices"

  # Valor requerido por Kong para la credencial.
  # No es la contraseña de Keycloak.
  secret: "app-searchia-jwt-secret"

  algorithm: RS256

  rsa_public_key: |
    -----BEGIN PUBLIC KEY-----
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAswXQ0z2L1mNaY6qSjoz8nr5S61kJxg3A
    HBLcFI+wX1P8vqx3AEbWQyNefLphDflM0o5Mg6ZA+bdBUmtsB3ikh23QGMeW+DlC+ZDb2vpX7TGD
    Fbe3rxPgaG4/fkxxKzr84Q19VPPhiFQUriS+jdB4UZys071o+kfCHAreINGZOoHFVCBOaFIH47/x
    tAsmVDeUGpgnrfueI/hw7xOALU3OQaTP5oRk46laFZsFyvxckWuKaoT8qNBk/H+Tu6eqbKUlSpIL
    E6/WN1ho6ltjGUIPDeHLIljAjI7ZCoNYOOG/1s6I2Z7d5hu5jaI83HZk1Y6KBpNIyd9Xzb4ojB28
    j0qY6wIDAQAB
    -----END PUBLIC KEY-----