apiVersion: configuration.konghq.com/v1
kind: KongConsumer
metadata:
  name: app-searchia-jwt-client
  namespace: applications
  annotations:
    kubernetes.io/ingress.class: kong
username: app-searchia-jwt-client
credentials:
  - app-searchia-jwt-credential