apiVersion: v1
kind: Secret
metadata:
  name: app-searchia-api-key
  namespace: applications
  labels:
    konghq.com/credential: key-auth
type: Opaque
stringData:
  kongCredType: key-auth
  key: app-searchia-test-123