# HTTP
quarkus.http.port=8080
quarkus.devservices.enabled= false
quarkus.datasource.devservices.enabled= false

##config azure SEARCH AI
azure.search.endpoint=https://rag-framework-search.search.windows.net
azure.search.index-name=rag-1786452219320
azure.search.api-key=${AZURE_SEARCH_API_KEY}

##config azure openai
azure.openai.endpoint=https://lmgomez-5706-resource.services.ai.azure.com/openai/v1
azure.openai.api-key=${AZURE_OPENAI_KEY}
azure.openai.deployment= gpt-5-mini-1

#cors
quarkus.http.cors.enabled=true
quarkus.http.cors.origins=*
